---
- name: Install JFrog Artifactory
  hosts: jfrog
  remote_user: ec2-user
  gather_facts: no
  tasks:
  - name: JFrog Installer
    ansible.builtin.shell:
      cmd: wget -O /tmp/artifactory-pro.rpm "https://releases.jfrog.io/artifactory/artifactory-pro-rpms/jfrog-artifactory-pro/jfrog-artifactory-pro-7.9.0.rpm"
    tags: jfrog

  - name: Install JFrog
    ansible.builtin.yum:
      name: '/tmp/artifactory-pro.rpm'
      state: present
    tags: jfrog

  - name: Start JFrog
    ansible.builtin.systemd:
      name: artifactory.service
      state: started
    tags: jfrog
